const Categoria = [
    { Name: "+ TESTARUDO", Icon: "" },
    { Name: "+ ENÉRGICO", Icon: "" },
    { Name: "+ DIVERTIDO", Icon: "" },
    { Name: "+ ESTRATEGA", Icon: "" },
    { Name: "+ SIMPATICO", Icon: "" },
    { Name: "+ APLICADO", Icon: "" },
    { Name: "+ TRANQUILO", Icon: "" },
    { Name: "+ OPTIMISTA", Icon: "" },
    { Name: "+ CREATIVO", Icon: "" },
    { Name: "+ EMPATICO", Icon: "" },
    { Name: "+ GUAPO / A", Icon: "" },
    { Name: "+ ASTUTO", Icon: "" },
    { Name: "+ COLABORATIVO", Icon: "" },
    { Name: "+ GENUINO", Icon: "" },
    { Name: "+ INDISCRETO", Icon: "" },
    { Name: "+ PUNTUAL", Icon: "" },
    { Name: "+ EXIGENTE", Icon: "" },
    { Name: "+ TACAÑO", Icon: "" },
    { Name: "+ TIMIDO", Icon: "" },
    { Name: "+ INDEPENDIENTE", Icon: "" },
    { Name: "+ LÍDER", Icon: "" },
    { Name: "+ DIPLOMATICO", Icon: "" },
    { Name: "+ PRUDENTE", Icon: "" },
]